// tic-tac-toe-solid/src/App.tsx
import { Component, createSignal, For, Show } from "solid-js";
import { createStore } from "solid-js/store";

import styles from "./App.module.css";

const App: Component = () => {
  const [board, setBoard] = createStore([
    ["", "", ""],
    ["", "", ""],
    ["", "", ""],
  ]);
  const [currentPlayer, setCurrentPlayer] = createSignal("X");
  const [winner, setWinner] = createSignal<string | null>(null);

  function checkWinner() {
    for (let i = 0; i < board.length; i++) {
      // horizontal
      if (
        board[i][0] &&
        board[i][0] === board[i][1] &&
        board[i][1] === board[i][2]
      )
        return board[i][0];
      // vertical
      if (
        board[0][i] &&
        board[0][i] === board[1][i] &&
        board[1][i] === board[2][i]
      )
        return board[0][i];
    }
    // diagonal
    if (board[1][1]) {
      if (board[0][0] === board[1][1] && board[1][1] === board[2][2])
        return board[1][1];
      if (board[0][2] === board[1][1] && board[1][1] === board[2][0])
        return board[1][1];
    }

    return null;
  }

  function playTurn(i: number, j: number) {
    if (board[i][j]) return;
    if (winner()) return;
    setBoard(i, j, () => currentPlayer());
    setCurrentPlayer((currentPlayer) => (currentPlayer === "X" ? "O" : "X"));
    setWinner(() => checkWinner());
  }

  return (
    <>
      <div class={styles.board}>
        <For each={board}>
          {(row, i) => (
            <div class={styles.row}>
              <For each={row}>
                {(col, j) => (
                  <div class={styles.col} onClick={() => playTurn(i(), j())}>
                    {col}
                  </div>
                )}
              </For>
            </div>
          )}
        </For>
      </div>
      <Show when={winner()}>{(winner) => <p>Winner: {winner()}</p>}</Show>
      <Show when={!winner()}>
        {(winner) => <p>Current Player: {currentPlayer()}</p>}
      </Show>
      <button
        style="display: block"
        onClick={() => {
          setBoard([
            ["", "", ""],
            ["", "", ""],
            ["", "", ""],
          ]);
          setCurrentPlayer("X");
          setWinner(null);
        }}
      >
        Reset board
      </button>
    </>
  );
};

export default App;

// tic-tac-toe-svelte/src/App.svelte
<script lang="ts">
  import Counter from './lib/Counter.svelte'

  let board = [
    ['', '', ''],
    ['', '', ''],
    ['', '', '']
  ]
  let currentPlayer = "X"
  let winner = null

  function playTurn(x, y) {
    if (board[x][y]) return
    if (winner) return
    board[x][y] = currentPlayer
    currentPlayer = currentPlayer === 'X' ? 'O' : 'X'
    winner = checkWinner()
  }

  function checkWinner() {
    for (let row = 0; row < board.length; row++) {
      // horizontal
      if (board[row][0] && board[row][0] === board[row][1] && board[row][1] === board[row][2]) {
        return board[row][0]
      }
      // vertical
      if (board[0][row] && board[0][row] === board[1][row] && board[1][row] === board[2][row]) {
        return board[0][row]
      }
    }
    // diagonal
    if (board[1][1]) {
      if (board[0][0] === board[1][1] && board[1][1] === board[2][2]) return board[1][1]
      if (board[0][2] === board[1][1] && board[1][1] === board[2][0]) return board[1][1]
    }
  }
</script>

<main>
  <div class="card">
    <Counter />
  </div>

  <div class="board">
    {#each board as row, i}
      <div class="row">
        {#each row as col, j}
          <div class="col" on:click={() => playTurn(i, j)}>
            {col}
          </div>
        {/each}
      </div>
    {/each}
  </div>

  {#if winner}
    <p>Winner: {winner}</p>
  {:else}
    <p>Current player: {currentPlayer}</p>
  {/if}

  <button on:click={() => {
    board = [
      ['', '', ''],
      ['', '', ''],
      ['', '', '']
    ]
    currentPlayer = 'X'
    winner = null
  }}>
    Reset board
  </button>

</main>

<style>
  .board {
    display: flex;
    flex-direction: column;
  }

  .row {
    display: flex;
  }

  .col {
    width: 50px;
    height: 50px;
    background-color: lightblue;
    border: 1px solid black;
  }
</style>
